# =============================
# ppt_server.py - Slide Logic
# =============================
import os
import shutil
from typing import List
import requests
from pptx import Presentation
from pptx.util import Pt
from config import Config
from fastmcp import FastMCP

# --- Constants ---
BASE_DIR = r"C:\Users\gunta\Downloads\Calibo"
TEMP_FILE = os.path.join(BASE_DIR, "temp_presentation.pptx")
mcp = FastMCP("ppt-server")

def download_pexels_image(query: str, save_path: str) -> str | None:
    """Download the first image from Pexels for a given query."""
    api_key = Config.PEXELS_API_KEY
    headers = {"Authorization": api_key}
    search_url = f"https://api.pexels.com/v1/search?query={query}&per_page=1"
    try:
        resp = requests.get(search_url, headers=headers, timeout=10)
        if resp.status_code == 200:
            data = resp.json()
            photos = data.get("photos", [])
            if photos:
                img_url = photos[0]["src"]["large"]
                img_resp = requests.get(img_url, timeout=10)
                if img_resp.status_code == 200:
                    with open(save_path, "wb") as f:
                        f.write(img_resp.content)
                    return save_path
        return None
    except Exception:
        return None


@mcp.tool()
def add_slide_with_image(title: str, bullets: List[str]) -> str:
    """Add a slide with title, bullets, and a relevant image from Pexels."""
    try:
        if not os.path.exists(TEMP_FILE):
            return "Error: Presentation not initialized."

        prs = Presentation(TEMP_FILE)
        layout_idx = 3 if len(prs.slide_layouts) > 3 else 1
        slide_layout = prs.slide_layouts[layout_idx]
        slide = prs.slides.add_slide(slide_layout)

        # Title
        if slide.shapes.title:
            slide.shapes.title.text = title

        # Placeholders
        left_placeholder, right_placeholder = None, None
        for shape in slide.placeholders:
            if shape.placeholder_format.idx == 1:
                left_placeholder = shape
            elif shape.placeholder_format.idx == 2:
                right_placeholder = shape
        if not left_placeholder:
            for shape in slide.placeholders:
                if shape.placeholder_format.type == 2:
                    left_placeholder = shape
                    break
        if left_placeholder:
            tf = left_placeholder.text_frame
            tf.clear()
            for i, point in enumerate(bullets):
                if i == 0:
                    tf.text = point
                    for run in tf.paragraphs[0].runs:
                        run.font.size = Pt(18)
                else:
                    p = tf.add_paragraph()
                    p.text = point
                    p.level = 0
                    for run in p.runs:
                        run.font.size = Pt(18)

        # Image search
        bullet_keywords = ' '.join([b.split(':')[0] if ':' in b else b.split('.')[0] for b in bullets])
        pexels_query = f"{title} {bullet_keywords}"
        img_path = os.path.join(BASE_DIR, f"pexels_{title.replace(' ', '_')}.jpg")
        img_file = download_pexels_image(pexels_query, img_path)
        if img_file and os.path.exists(img_file):
            img_inserted = False
            if right_placeholder:
                try:
                    slide.shapes.add_picture(img_file, right_placeholder.left, right_placeholder.top, right_placeholder.width, right_placeholder.height)
                    img_inserted = True
                except Exception:
                    pass
            if not img_inserted:
                try:
                    slide.shapes.add_picture(img_file, left=400, top=150, width=400, height=300)
                except Exception:
                    pass

        prs.save(TEMP_FILE)
        return f"Slide with image added: {title}"
    except Exception as e:
        return f"[ERROR in add_slide_with_image] {str(e)}"

@mcp.tool()
def create_presentation(title: str) -> str:
    """Create a new PowerPoint presentation with a title slide."""
    try:
        prs = Presentation()
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by AgentSlides"
        prs.save(TEMP_FILE)
        return "Presentation created and saved to temp file"
    except Exception as e:
        return f"[ERROR in create_presentation] {str(e)}"


@mcp.tool()
def add_slide(title: str, bullets: List[str]) -> str:

    @mcp.tool()
    def add_slide(title: str, bullets: List[str]) -> str:
        """Add a slide with title and bullet points (no image)."""
        try:
            if not os.path.exists(TEMP_FILE):
                return "Error: Presentation not initialized."
            prs = Presentation(TEMP_FILE)
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = title
            tf = slide.placeholders[1].text_frame
            tf.clear()
            for i, point in enumerate(bullets):
                if i == 0:
                    tf.text = point
                else:
                    p = tf.add_paragraph()
                    p.text = point
                    p.level = 0
            prs.save(TEMP_FILE)
            return f"Slide added: {title}"
        except Exception as e:
            return f"[ERROR in add_slide] {str(e)}"


@mcp.tool()
def save_presentation(filename: str) -> str:
    """Save the current presentation to the specified filename."""
    try:
        if not os.path.exists(TEMP_FILE):
            return "Error: No presentation to save."
        final_path = os.path.join(BASE_DIR, os.path.basename(filename))
        shutil.copy(TEMP_FILE, final_path)
        return f"Presentation saved at: {final_path}"
    except Exception as e:
        return f"[ERROR in save_presentation] {str(e)}"



if __name__ == "__main__":
    mcp.run()